[build]
builder = "nixpacks"
buildCommand = "cd server && npx prisma generate"

[deploy]
startCommand = "cd server && npx prisma db push && pnpm start"
healthcheckPath = "/trpc"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
