[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter server run postinstall"

[deploy]
startCommand = "pnpm --filter server run db:push && pnpm --filter server start"
healthcheckPath = "/trpc"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
