[build]
builder = "railpack"
buildCommand = "pnpm install --ignore-scripts && pnpm --filter front build"

[deploy]
startCommand = "pnpm --filter front start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
