export enum Faction {
  HOLY_KNIGHTS = 'HOLY_KNIGHTS',
  LEGION = 'LEGION',
  ALCHEMISTS_LEAGUE = 'ALCHEMISTS_LEAGUE',
  DEATH_MARCH = 'DEATH_MARCH',
  CRIMSON_INQUISITION = 'CRIMSON_INQUISITION',
  BLOOD_PACT = 'BLOOD_PACT'
}
