export const GUILD_MESSAGE_MAX_LENGTH = 2000

export const GUILD_DESCRIPTION_MAX_LENGTH = 5000
export const GUILD_DESCRIPTION_HTML_MAX_LENGTH = 15000
export const GUILD_TITLE_MAX_LENGTH = 32
export const GUILD_TITLE_POOL_MAX_SIZE = 20
