[build]
builder = "nixpacks"

[deploy]
startCommand = "bunx prisma generate && bunx prisma db push && bun start"
healthcheckPath = "/trpc"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
